In [1]:
# IRIS Dataset

In [3]:
from sklearn.datasets import load_iris
#will import IRIS dataset
# i need it

In [4]:
iris= load_iris()
# upload it


In [5]:
test_idx = [0, 50 ,100]

In [6]:
import numpy as np
from sklearn import tree #Decision Tree

In [7]:
#separate training from testing
train_target=np.delete(iris.target, test_idx) # class- label
train_data=np.delete(iris.data, test_idx, axis=0) #feature
# axis=0 , delete one complete row

In [8]:

# save algorithm in clf
# not trained yet
clf_1 = tree.DecisionTreeClassifier()


In [9]:
#Train
clf_1.fit(train_data, train_target)# train the model

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [13]:
test_target = iris.target[test_idx]  # test the three samples
test_data = iris.data[test_idx] # =
print (test_target)
print(test_data)

[0 1 2]
[[5.1 3.5 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.3 3.3 6.  2.5]]


In [14]:
y_pred=clf_1.predict(test_data) #testing
print(y_pred)

[0 1 2]


In [15]:
from sklearn.metrics import accuracy_score
accuracy_score(test_target, y_pred)

1.0

In [16]:
from sklearn.datasets import load_breast_cancer
data = load_breast_cancer()

In [20]:
test_idx = [10,200,100,500]

In [23]:
import numpy as np
from sklearn.svm import SVC

In [25]:
#saperate training from testing
train_target=np.delete(data.target, test_idx) # class- label
train_data=np.delete(data.data, test_idx, axis=0) #feature
# axis=0 , delete one complete row

In [37]:

# save algorithm in clf
# not trained yet
clf_1 = SVC(gamma = "auto", C = 1, kernel= 'linear' )

In [38]:
#Train
clf_1.fit(train_data, train_target)# train the model

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [32]:
test_target = data.target[test_idx]  # test the three samples
test_data = data.data[test_idx] # =
print (test_target)
print(test_data)

[0 1 0 1]
[[1.799e+01 1.038e+01 1.228e+02 1.001e+03 1.184e-01 2.776e-01 3.001e-01
  1.471e-01 2.419e-01 7.871e-02 1.095e+00 9.053e-01 8.589e+00 1.534e+02
  6.399e-03 4.904e-02 5.373e-02 1.587e-02 3.003e-02 6.193e-03 2.538e+01
  1.733e+01 1.846e+02 2.019e+03 1.622e-01 6.656e-01 7.119e-01 2.654e-01
  4.601e-01 1.189e-01]
 [1.223e+01 1.956e+01 7.854e+01 4.610e+02 9.586e-02 8.087e-02 4.187e-02
  4.107e-02 1.979e-01 6.013e-02 3.534e-01 1.326e+00 2.308e+00 2.724e+01
  7.514e-03 1.779e-02 1.401e-02 1.140e-02 1.503e-02 3.338e-03 1.444e+01
  2.836e+01 9.215e+01 6.384e+02 1.429e-01 2.042e-01 1.377e-01 1.080e-01
  2.668e-01 8.174e-02]
 [1.361e+01 2.498e+01 8.805e+01 5.827e+02 9.488e-02 8.511e-02 8.625e-02
  4.489e-02 1.609e-01 5.871e-02 4.565e-01 1.290e+00 2.861e+00 4.314e+01
  5.872e-03 1.488e-02 2.647e-02 9.921e-03 1.465e-02 2.355e-03 1.699e+01
  3.527e+01 1.086e+02 9.065e+02 1.265e-01 1.943e-01 3.169e-01 1.184e-01
  2.651e-01 7.397e-02]
 [1.504e+01 1.674e+01 9.873e+01 6.894e+02 9.883e-02 1.364

In [39]:
clf_1.predict(test_data) #testing

array([0, 1, 0, 1])